/**
 * Application-wide error codes.
 *
 * Used in API responses so clients can programmatically
 * handle specific error conditions.
 */

export const ERROR_CODES = Object.freeze({
  // Auth
  AUTH_INVALID_CREDENTIALS: 'AUTH_INVALID_CREDENTIALS',
  AUTH_TOKEN_EXPIRED: 'AUTH_TOKEN_EXPIRED',
  AUTH_TOKEN_INVALID: 'AUTH_TOKEN_INVALID',
  AUTH_USER_EXISTS: 'AUTH_USER_EXISTS',
  AUTH_USER_NOT_FOUND: 'AUTH_USER_NOT_FOUND',

  // Meeting
  MEETING_NOT_FOUND: 'MEETING_NOT_FOUND',
  MEETING_INVALID_STATUS: 'MEETING_INVALID_STATUS',
  MEETING_ALREADY_ACTIVE: 'MEETING_ALREADY_ACTIVE',

  // Transcript
  TRANSCRIPT_NOT_FOUND: 'TRANSCRIPT_NOT_FOUND',
  TRANSCRIPT_MEETING_NOT_ACTIVE: 'TRANSCRIPT_MEETING_NOT_ACTIVE',

  // Validation
  VALIDATION_ERROR: 'VALIDATION_ERROR',

  // General
  NOT_FOUND: 'NOT_FOUND',
  INTERNAL_ERROR: 'INTERNAL_ERROR',
  RATE_LIMIT_EXCEEDED: 'RATE_LIMIT_EXCEEDED',
});
